name: "Billance"
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "6969:5432"
    environment:
      POSTGRES_USER: jeanquille
      POSTGRES_PASSWORD: root
      POSTGRES_DB: billance_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data: